### ISSUE TITLE
[System/GameOver] not able to see in oculus screen

### ISSUE THREAD

**Issue by Ofiun** [Ofiun/tylenol#10]
캔버스에 그려진 게임오버화면을 오큘러스 화면에서 확인할 수 없음..
쉬운 문제 같은데 아직 해결 못함.

**Comment by minz95** [comment]
oculus canvas example에 있는 설정을 적용해도 안보이나요

**Comment by Ofiun** [comment]
Canvas Example 설정이 무엇인지 잘모르겠습니당.. 담에 알려주세여
우선 Canvas - Render Mode 를 'Screen Space - Overlay' 에서 'World Space' 로 바꾸고 공간위에 올렸습니당.. 오버레이로 하니까 렌더링하는데 시간 오래걸리고 뜨지도 않길래..
