### ISSUE TITLE
[Screen/Interstage] better to have graphical interstage screen

### ISSUE THREAD

**Issue by Ofiun** [Ofiun/tylenol#13]
스테이지 넘어갈때 그래픽 스크린이 있으면 나을듯함..

**Comment by minz95** [comment]
개발 로드를 줄이기 위해 꼭 필요할지 생각해봅시다... + interstage screen 보여주는 시간이 너무 짧은 것 같이 느껴지네요

**Comment by Ofiun** [comment]
씬 안에서 보드UI 형태로 표시.
