### ISSUE TITLE
[Object/Shatter] Objects using Box Collider are not shattered well

### ISSUE THREAD

**Issue by Ofiun** [Ofiun/tylenol#21]
.

**Comment by Ofiun** [comment]
메쉬 콜라이더의 경우 섀터됨과 함께 콜라이더도 나누어지는 듯 하나 박스콜라이더는 박스형태가 유지되는듯함..

**Comment by Ofiun** [comment]
![problem](https://user-images.githubusercontent.com/28622841/54808971-2ab0aa00-4cc5-11e9-8b89-39d563b1d6b7.jpg)

**Comment by Ofiun** [comment]
섀터툴에서 오브젝트를 부수고 난뒤 박스컬라이더의 경우 속성을 그대로 복사하는듯함..

**Comment by Ofiun** [comment]
![boxCollider2ConvexMeshCollider](https://user-images.githubusercontent.com/28622841/54859936-42843e80-4d56-11e9-8203-234fe37c0fad.jpg)

**Comment by Ofiun** [comment]
메시 콜라이더를 갖지 않는 오브젝트의 경우 박스 콜라이더가 있으면 전부 없애주고 부서진 모양에 맞추어 컨벡스 메시 콜라이더를 새로 생성하도록 섀터툴 코드를 수정.

**Comment by minz95** [comment]
닫아도 되는 이슈인가요?

**Comment by Ofiun** [comment]
issue #24 와 연결되어서 닫아도 상관없을것 같습니다!
