### ISSUE TITLE
[Object/Shatter] As being hit and shattered, Objects go through the walls and floor.

### ISSUE THREAD

**Issue by Ofiun** [Ofiun/tylenol#24]
.

**Comment by Ofiun** [comment]
특히 물체를 위에서 아래로 치면 상당 경우 바닥을 지나쳐 사라지는 거 같음..

**Comment by Ofiun** [comment]
메시 콜라이더 설정과 관련있는지 확인해 봄. 
메시 콜라이더의 이름이 비어있어도 메시 자체는 있는 것으로 확인.. 
(원인 미파악)

**Comment by minz95** [comment]
벽과 바닥의 collider가 trigger이거나 한건 아니죠?
아니면 부딪혔을때, 매우 강하게 튕겨나가서 사라진것처럼 보이는건가요? (scene에서 방향을 확인) 그럴 경우, 튕겨나가지 않도록 physics material 설정을 바꿔줍시다.

**Comment by minz95** [comment]
shatter tool에서 새로 생성된 object의 위치를 재조정 해줌으로써 해결.
